import { randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

if (process.argv.includes("--help") || process.argv.includes("-h")) {
  console.log("Usage: AUTH_SESSION_SECRET=current API_AUTH_TOKEN=current [ROTATION_ENV_FILE=.secrets.rotation.env] npm run ops:rotate-secrets");
  process.exit(0);
}

const nextSessionSecret = process.env.NEXT_AUTH_SESSION_SECRET || token(48);
const nextApiToken = process.env.NEXT_API_AUTH_TOKEN || `cjlass2_${token(32)}`;
const previousSessionSecrets = unique([
  process.env.AUTH_SESSION_SECRET,
  ...(process.env.AUTH_SESSION_PREVIOUS_SECRETS || "").split(","),
]);
const previousApiTokens = unique([
  process.env.API_AUTH_TOKEN,
  ...(process.env.API_AUTH_TOKEN_PREVIOUS || "").split(","),
]);

const lines = [
  "# Generated by scripts/ops/rotate-secrets.mjs",
  "# Apply current values first, deploy, wait for old sessions to expire, then remove *_PREVIOUS entries.",
  `AUTH_SESSION_SECRET=${nextSessionSecret}`,
  `AUTH_SESSION_PREVIOUS_SECRETS=${previousSessionSecrets.join(",")}`,
  `API_AUTH_TOKEN=${nextApiToken}`,
  `API_AUTH_TOKEN_PREVIOUS=${previousApiTokens.join(",")}`,
];

const output = `${lines.join("\n")}\n`;
if (process.env.ROTATION_ENV_FILE) {
  const target = resolve(process.env.ROTATION_ENV_FILE);
  writeFileSync(target, output, { mode: 0o600 });
  console.log(JSON.stringify({ ok: true, rotationEnvFile: target, previousSessionSecretCount: previousSessionSecrets.length, previousApiTokenCount: previousApiTokens.length }, null, 2));
} else {
  process.stdout.write(output);
}

function token(bytes) {
  return randomBytes(bytes).toString("base64url");
}

function unique(values) {
  return [...new Set(values.map((value) => value?.trim()).filter(Boolean))];
}
